# Generated by Django 5.1.6 on 2025-03-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('HR', 'Hairstyle'), ('HC', 'Hair colour'), ('HS', 'Hair Spa')], default='HR', max_length=2),
        ),
    ]
