# Generated by Django 5.1.6 on 2025-05-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_services_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
