# Generated by Django 5.1.6 on 2025-05-11 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(to='userauth.services'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default='09:00'),
        ),
    ]
