# Generated by Django 5.1.6 on 2025-05-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_remove_booking_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_services',
            field=models.ManyToManyField(blank=True, related_name='additional_bookings', to='userauth.services'),
        ),
    ]
