# Generated by Django 5.1.6 on 2025-05-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_booking_additional_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyrecord',
            name='free_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loyaltyrecord',
            name='service_taken',
            field=models.IntegerField(default=0),
        ),
    ]
