# Generated by Django 5.1.6 on 2025-05-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_alter_loyaltyrecord_free_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loyaltyprogram',
            old_name='service_id',
            new_name='service',
        ),
    ]
