# Generated by Django 5.1.6 on 2025-05-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_booking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
    ]
