# Generated by Django 5.1.6 on 2025-05-25 08:44

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_remove_booking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=10, null=True, region='NP'),
        ),
    ]
