# Generated by Django 5.1.6 on 2025-07-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
